### ISSUE TITLE
Orient

### ISSUE THREAD

**Issue by NicoRenaud** [DeepRank/pdb2sql#28]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to fully orient the structure along the cartesian axis. So far `align` only aligns the larger/smaller pca eigenvector to one of the axis but leave the other two axis unchanged

**Describe the solution you'd like**
Would be great to be for example able to write something like `orient(pdb, axis='z')` and have all pca vectors aligned along the x,y,z axis (with here the larger vect aligned along the 'z' direction)

https://pymolwiki.org/index.php/Orient,
https://nmr.cit.nih.gov/xplor-nih/xplorMan/node159.html, https://salilab.org/modeller/9v4/manual/node180.html

**Comment by CunliangGeng** [comment]
To be consistent with Haddock and pymol, the largest vector should be aligned to 'x' direction.
