### ISSUE TITLE
update doc with the new align feature

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/pdb2sql#29]

**Comment by LilySnow** [comment]
Added an example file `align_pdb.py` to the example folder.

**Comment by LilySnow** [comment]
Can we put these examples in https://pdb2sql.readthedocs.io/en/latest/tutorial.html

**Comment by NicoRenaud** [comment]
Hi Li, I've added new sections to  the doc about align / superpose and a couple of other things. The 10 min tutorial is really meant to give the essentials so I don't think the example fit there. The example you provided are however included in the repo under `example/` and we should at some point review the tutorial. In the mean time I think we can close this issue
