### ISSUE TITLE
pytest failed

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/pdb2sql#4]
pytest failed. I guess it is due to the recent update. 

> E       FileNotFoundError: [Errno 2] No such file or directory: 'pdb/target136-scoring_0506_conv.pdb'
> 
> ../pdb2sql/pdb2sqlcore.py:193: FileNotFoundError

**Comment by NicoRenaud** [comment]
should work now.

**Comment by fmeiman** [comment]
`pytest` fails at the following step:

	test_structureSimilarity.py:15:
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	../pdb2sql/StructureSimilarity.py:211: in compute_irmsd_fast
		self.compute_izone(cutoff,save_file=True,filename=izone)
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

	self = <pdb2sql.StructureSimilarity.StructureSimilarity object at 0x2aaabef71978>, cutoff = 10, save_file = True
	filename = '1AK4.izone'

		def compute_izone(self,cutoff=5.0,save_file=True,filename=None):

			sql_ref = interface(self.ref)
			contact_ref = sql_ref.get_contact_atoms(cutoff=cutoff,extend_to_residue=True,return_only_backbone_atoms=True)
	>       index_contact_ref = contact_ref[0]+contact_ref[1]
	E       KeyError: 0

	../pdb2sql/StructureSimilarity.py:265: KeyError

**Comment by NicoRenaud** [comment]
Fixed the bug in `compute_izone` I'll test it again and re-close the issue if that passes. Should definitely invest time in setting up CI

**Comment by NicoRenaud** [comment]
close for now
