### ISSUE TITLE
Update doc on structureSimilarity methods

### ISSUE THREAD

**Issue by CunliangGeng** [DeepRank/pdb2sql#56]
- [ ] explain the fast and slow methods of `structureSimilarity` 
- [ ] provide a speed performance benchmark for `structureSimilarity` methods

**Comment by NicoRenaud** [comment]
I think we should actually refator entirely this file. I didn't do a great job  .... 
We could use the `many2sql` class as a base
maybe we should choose between the fast and slow  methods or provide one class with a keyword to choose which method to use
