### ISSUE TITLE
pdb line is longer than 80

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/pdb2sql#74]
**Describe the bug**
When using pdb2sql to calculate iRMSD of Zdock models, pdb2sql reports an error: pdb line is longer than 80. 

It is not clear to me why we need this function `_format_pdb_linelength` and why we have 80 as a cutoff. It seems that we can simply increase 80 to 150, for example. 

**Error message:**

> File "/Applications/anaconda3/lib/python3.7/site-packages/pdb2sql/pdb2sqlcore.py", line 136, in _create_table
>     line = pdb2sql._format_pdb_linelength(line)
>   File "/Applications/anaconda3/lib/python3.7/site-packages/pdb2sql/pdb2sqlcore.py", line 255, in _format_pdb_linelength
>     f'pdb line is longer than 80:\n{pdb_line}')
> ValueError: pdb line is longer than 80:
> ATOM      1  N   GLN A   1       1.795  -7.034  21.703 19     1 1.63          -.15

**To Reproduce**

```
model = 'complex_6.pdb'
ref = 'cleaned_1oga_b_differently_numbered.pdb'
sim = StructureSimilarity(model,ref)
irmsd = sim.compute_irmsd_pdb2sql(method='svd')
```
[complex_6.pdb.txt](https://github.com/DeepRank/pdb2sql/files/8956047/complex_6.pdb.txt)
[cleaned_1oga_b_differently_numbered.pdb.txt](https://github.com/DeepRank/pdb2sql/files/8956048/cleaned_1oga_b_differently_numbered.pdb.txt)

**Comment by CunliangGeng** [comment]
The issue is reopened, is there any more questions about it?

**Comment by NicoRenaud** [comment]
We rarely do anything with then data after the contained in the columns that are after the coordinates in the PDB. So we could limit the parsing to the cols up to the xyz coordinate. Then we could read the ZDOCK files ...
